### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by suvozy** [RimeOfficial/Brand#1]
# Zapf Dingbats

![](../raw/efaffda7f60cd0359a15595945fdf12ef8ee2f09/logo_glyph%20design.png)

![screen shot 2016-08-21 at 5 14 31 pm](https://cloud.githubusercontent.com/assets/5635088/17998229/e32d309e-6b90-11e6-853e-fb970d978b41.png)

**Comment by suvozit** [comment]
# Menlo Regular
![](../raw/64e3a78a1063c7b7fc0bcea3b20eb2f9e9a8f196/logo_glyph%20design.png)

## References
- Character Encodings - Legacy Encodings - Adobe Zapf Dingbats - Heavy Asterisk
  http://www.kreativekorp.com/charset/encoding.php?name=Adobe+Zapf+Dingbats&char=51

**Comment by suvozy** [comment]
# Menlo Regular https://github.com/RimeOfficial/branding/commit/64e3a78a1063c7b7fc0bcea3b20eb2f9e9a8f196

![](../raw/64e3a78a1063c7b7fc0bcea3b20eb2f9e9a8f196/logo_glyph%20design.png)

## References
- Character Encodings - Legacy Encodings - Adobe Zapf Dingbats - Heavy Asterisk
  http://www.kreativekorp.com/charset/encoding.php?name=Adobe+Zapf+Dingbats&char=51

**Comment by suvozy** [comment]
![anti-aliasing-01-01](https://cloud.githubusercontent.com/assets/5635088/17998165/9ddc72b6-6b90-11e6-848a-7faf770d5583.png)
![anti-aliasing-02-01](https://cloud.githubusercontent.com/assets/5635088/17998164/9dd81e82-6b90-11e6-80c0-da84f8c15526.png)
![anti-aliasing-03-01](https://cloud.githubusercontent.com/assets/5635088/17998163/9dd7e0ac-6b90-11e6-9d79-bc8bf3bb3fee.png)

[anti-aliasing.ai.zip](https://github.com/RimeOfficial/brand/files/438810/anti-aliasing.ai.zip)
